[config]
model="gemini/gemini-2.0-flash-exp"
fallback_models=["gemini/gemini-2.0-flash-exp"]

[pr_description] # /describe
publish_labels = false
enable_pr_type = false
extra_instructions = "Descriptionの説明は日本語で回答してください" # 単に日本語で回答してと伝えても英語が出力されてしまう

[pr_reviewer] # /review
extra_instructions = "日本語で回答してください"

[pr_questions] # /ask
extra_instructions = "日本語で回答してください"

[pr_code_suggestions] # /improve
extra_instructions = "日本語で回答してください"